### ISSUE TITLE
recreate site in bootstrap

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-samincusa#1]
@AaronAguilar or @purplyrocky you two can decide which of you takes this task

Recreate this site using bootstrap. It's a simple one page site that can probably get done in 1hr flat. 

Open the "SAM_home.html" file to get a reference of what it's supposed to look like. 

due date:
7/17/15  3pm

**Comment by rodneystrong** [comment]
I know i already told you in person yesterday, but here it is again just in case: 
samincusa.com

**Comment by AaronAguilar** [comment]
Here's what it looks like. http://editllc.github.io/client-samincusa/

**Comment by rodneystrong** [comment]
good job sir!
